name: Matplotplusplus

on: [ push, pull_request ]

jobs:
  Build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows/2019/Static/X86/Release",
            os: windows-2019,
            config: Release,
            args: -G "Visual Studio 16 2019" -A Win32,
          }
          - {
            name: "Windows/2019/Static/X64/Release",
            os: windows-2019,
            config: Release,
            args: -G "Visual Studio 16 2019" -A x64,
          }
          - {
            name: "Ubuntu/18.04/Static/X64/Release",
            os: ubuntu-18.04,
            config: Release,
            args: "",
          }
          - {
            name: "MacOSX/10.15/Static/X64/Release",
            os: macos-10.15,
            config: Release,
            args: "",
          }
    steps:
      - uses: actions/checkout@v2
      - name: Create Work Dir
        run: mkdir build
      - name: Configure
        working-directory: ./build
        run: |
          cmake .. ${{ matrix.config.args }} -DCMAKE_BUILD_TYPE=${{ matrix.config.config }}
      - name: Build
        working-directory: ./build
        run: cmake --build . -j 2 --config ${{ matrix.config.config }}
      - name: Test
        working-directory: ./build
        run: ctest -j 2
