name: Docs Generator

on: push

jobs:
  generateDOC:
    name: Docs Generator
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Generate Table of Contents
        uses: technote-space/toc-generator@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_HEADER_LEVEL: 3
          FOLDING: true
      - name: Update Contributors
        uses: akhilmhdh/contributors-readme-action@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          image_size: 100
          columns_per_row: 6
      - name: Download mdsplit
        uses: carlosperate/download-file-action@v1.0.3
        id: download-mdsplit
        with:
          file-url: 'https://github.com/alandefreitas/mdsplit/releases/download/v0.1.1/Executable.Linux.zip'
          file-name: 'mdsplit.zip'
          location: '.'
      - name: Unzip mdsplit
        run: |
          unzip mdsplit.zip
          rm -f mdsplit.zip
          sudo chmod +x mdsplit
          ls
      - name: Generate Documentation Source
        run: ./mdsplit -r alandefreitas/matplotplusplus
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Mkdocs Material
        run: pip install mkdocs-material
      - name: Install Awesome Pages Plugin # https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
        run: pip install mkdocs-awesome-pages-plugin
      - name: Deploy mkdocs to gh-pages branch
        run: mkdocs gh-deploy --force
